# One-Hot Encoding in NLP

## Definition

**One-Hot Encoding** is a text representation technique used in Natural Language Processing (NLP) where each unique word in the vocabulary is represented as a **binary vector**.

- The length of the vector is equal to the size of the vocabulary.
- Only **one element is 1**, indicating the position of the word.
- All remaining elements are **0**.

> **Formula:**
>
> If the vocabulary size is **V**, then each word is represented by a vector of length **V**.

---

## Example

### Step 1: Create the Vocabulary

```python
Vocabulary = ["I", "love", "NLP", "and", "AI"]
```

Vocabulary Size = **5**

---

### Step 2: Generate One-Hot Vectors

| Word | One-Hot Representation |
|------|-------------------------|
| I | `[1, 0, 0, 0, 0]` |
| love | `[0, 1, 0, 0, 0]` |
| NLP | `[0, 0, 1, 0, 0]` |
| and | `[0, 0, 0, 1, 0]` |
| AI | `[0, 0, 0, 0, 1]` |

---

## Sentence Representation

Sentence:

```text
I love NLP
```

One-Hot Representation:

```text
I     → [1, 0, 0, 0, 0]

love  → [0, 1, 0, 0, 0]

NLP   → [0, 0, 1, 0, 0]
```

---

# Visual Representation

```
Vocabulary

      I   love   NLP   and   AI
      ↓     ↓      ↓     ↓     ↓

I    → 1     0      0     0     0

love → 0     1      0     0     0

NLP  → 0     0      1     0     0

and  → 0     0      0     1     0

AI   → 0     0      0     0     1
```

---

# Python Implementation

```python
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Dataset
words = np.array([
    ["I"],
    ["love"],
    ["NLP"]
])

# Create Encoder
encoder = OneHotEncoder(sparse_output=False)

# Transform Data
encoded = encoder.fit_transform(words)

print(encoded)
```

### Output

```python
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

---

# Advantages

- ✅ Simple to understand and implement.
- ✅ Easy to convert categorical words into numerical vectors.
- ✅ Suitable for small vocabularies.
- ✅ Commonly used as a preprocessing technique in basic Machine Learning models.

---

# Disadvantages

- ❌ Produces **high-dimensional vectors** for large vocabularies.
- ❌ Creates **sparse matrices** (mostly zeros).
- ❌ Does **not capture semantic relationships** between words.
- ❌ Memory inefficient for large datasets.

---

# Limitation Example

Consider two semantically similar words:

| Word | Vector |
|------|--------|
| King | `[1, 0, 0, 0]` |
| Queen | `[0, 1, 0, 0]` |

Although **King** and **Queen** have similar meanings, their vectors are completely different.

Therefore, One-Hot Encoding **cannot understand word similarity or context**.

---

# Why Modern NLP Uses Word Embeddings

Instead of sparse vectors, modern NLP models use **dense vector representations (Embeddings)**.

Example:

```text
King   = [0.25, 0.81, -0.12, 0.43, ...]

Queen  = [0.28, 0.79, -0.10, 0.45, ...]
```

These vectors capture semantic relationships between words.

Examples of embedding techniques:

- Word2Vec
- GloVe
- FastText
- BERT Embeddings
- Sentence Transformers

---

# Comparison

| Feature | One-Hot Encoding | Word Embeddings |
|----------|------------------|-----------------|
| Vector Type | Sparse | Dense |
| Captures Meaning | ❌ No | ✅ Yes |
| Memory Efficient | ❌ No | ✅ Yes |
| Handles Similar Words | ❌ No | ✅ Yes |
| Vocabulary Size | Very Large | Fixed Embedding Size |
| Used in Modern LLMs | ❌ No | ✅ Yes |

---

# Summary

One-Hot Encoding is a basic text representation technique where each word is represented by a unique binary vector. While it is simple and effective for small datasets, it suffers from high dimensionality, sparse representations, and an inability to capture semantic meaning. These limitations led to the development of **Word Embeddings**, which are now the standard representation method in modern NLP and Large Language Models (LLMs).